steps:
  - label: ":python: Test Mujoco Python Script"
    command: "python mujoco/mujoco_test.py"
    agents:
      queue: "python"

  - label: ":shell: Run Bash Script"
    command: "bash mujoco/run_bash_engaging.sh"
    agents:
      queue: "bash"
